[tool.poetry]
name = "hashcord-ext-menus-views"
version = "0.1.0"
description = "A discord.ext.menus Menu backed by Views and Buttons instead of reactions."
authors = ["Oliver Ni <oliver.ni@gmail.com>"]
license = "MIT"
packages = [
    { include = "hashcord" }
]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = { git = "https://github.com/ExpertTutorials/Hashcord.git", branch = "master" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
